include_defs('//bucklets/maven_jar.bucklet')

VER = '2.12-SNAPSHOT'
REPO = MAVEN_LOCAL

maven_jar(
  name = 'plugin-api',
  id = 'com.google.gerrit:gerrit-plugin-api:' + VER,
  sha1 = 'c6871ac4b8f36d00000f5705ea26a88252d5360f',
  attach_source = False,
  repository = REPO,
  license = 'Apache2.0',
)

